### ISSUE TITLE
Support for picker inside Repeaters

### ISSUE THREAD

**Issue by krisj** [trk/FieldtypeFontIconPicker#2]
Absolutely love this Fieldtype! Its very useful, but I see it doesnt work properly when inside repeaters. Any plans to support it?

I can sort of do a half workaround by turning off AJAX loading in repeaters, but it's a usability hit for users.

probably needs some hook into ajax call by the repeater?

I am trying this on PW 3.12

**Comment by trk** [comment]
I updated module, i think it will work now. Can you check and confirm ?

**Comment by PittTango** [comment]
I can confirm that it's now working in repeaters, but if you have it hidden until certain conditions are met(visibility settings), you only get a text dropdown of icons when you meet the conditions, not the icons. I haven't been able to check yet if that's a general visibility issue or specific to repeaters.
