### ISSUE TITLE
UiKit icons

### ISSUE THREAD

**Issue by krisj** [trk/FieldtypeFontIconPicker#4]
For a fresh install (FieldtypeFontIconPicker 0.1.6) to show UiKit icons in Admin I had to manually add 

`$config->scripts->append($config->urls->root . "site/templates/js/uikit-icons.min.js?v=$version");`

to the head of the /AdminThemeUikit/_head.php

Now it works but did I miss anything?

**Comment by trk** [comment]
I am using modified version of [AdminThemeUikit theme](https://github.com/trk/AdminThemeUikit) this is why i missed this js file for original theme, i am loading this js file on modified version. You putted js file to right place [like here](https://github.com/trk/AdminThemeUikit/blob/master/_head.php#L27) on my modified theme. For original theme i will make a request.

**Comment by trk** [comment]
here is request : https://github.com/ryancramerdesign/AdminThemeUikit/issues/24
